### PR TITLE
Add directions to create small reproducible example

### PR DESCRIPTION
**Pull request by chacalle**
## Describe changes

Encourage creating a small reproducible example for code. Also include link to reprex R package which looks really useful.

### CODE REVIEW

**Review by krpaulson — APPROVED** [review]
Is this meant to be an either/or with the "Steps to reproduce the behavior" bit?

**Comment by krpaulson** [comment]
Do you understand how to use `reprex` @chacalle? I'm unsure what "copy this code onto your clipboard" means since I tried `cmd + c` and that didn't do the trick. Output:
```
> reprex()
No input provided and clipboard is not available.
Rendering reprex...
Clipboard on X11 requires 'xclip' (recommended) or 'xsel'.
Unable to put result on the clipboard. How to get it:
  * Capture what `reprex()` returns.
  * Consult the output file. Control via `outfile` argument.
Path to `outfile`:
  * /tmp/RtmpOSnnXf/reprex3643c121d0/reprex_reprex.md
Open the output file for manual copy?
1: yes
2: no
```

**Comment by chacalle** [comment]
> Do you understand how to use `reprex` @chacalle? I'm unsure what "copy this code onto your clipboard" means since I tried `cmd + c` and that didn't do the trick. Output:

Hmm I just tried this:
1. Copy `rbinom(3, size = 10, prob = 0.5)` with cmd + c
2. Run reprex with no input arguments
```
> reprex::reprex()
ℹ Rendering reprex...
✓ Rendered reprex is on the clipboard.
```
3. Paste output that is automatically on my clipboard
``` r
rbinom(3, size = 10, prob = 0.5)
#> [1] 2 8 2
```

<sup>Created on 2021-02-01 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by chacalle** [comment]
Or I'm able to run it like this with the code expression inside

`reprex::reprex(rbinom(3, size = 10, prob = 0.5))`

**Comment by krpaulson** [comment]
Okay I got this to work on my local computer but not on the cluster (IDE, v2020.0.13). Following your steps 1 and 2 I get:
```
> reprex::reprex()
No input provided and clipboard is not available.
Rendering reprex...
Error in default_load_hook() : 
  Unable to find environment file in temporary directory. Try restarting R session.
```
Then after restarting my R session I still get the error from above.

**Comment by chacalle** [comment]
I confirmed this at least works on v2021.1.1

**Pull request merged**
